### ISSUE TITLE
Thank you very much for your plugin. have a small suggestion.

### ISSUE THREAD

**Issue by kukuma2020** [leopardbyte/pengu-auto-queue#1]
Thank you very much for your plugin, but I didn't find the option for INTRO_BOT when I used it. Could you add it? Thanks!

**Comment by leopardbyte** [comment]
[index.zip](https://github.com/user-attachments/files/16569279/index.zip)
here ya go replace the index.js file with this one

**Comment by kukuma2020** [comment]
thx bro, but its working on ARAM, I think the QueueMap ID for INTRO_BOT is 830, not 450?
